// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShedAndFed.Data;

#nullable disable

namespace ShedAndFed.Data.Migrations
{
    [DbContext(typeof(ReptileDbContext))]
    [Migration("20260331124216_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ShedAndFed.Entities.FeedingLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReptileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasEaten")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.HasIndex("ReptileId");

                    b.ToTable("FeedingLogs");
                });

            modelBuilder.Entity("ShedAndFed.Entities.Reptile", b =>
                {
                    b.Property<int>("ReptileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LengthCm")
                        .HasColumnType("REAL");

                    b.Property<string>("Morph")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("ReptileId");

                    b.ToTable("Reptiles");
                });

            modelBuilder.Entity("ShedAndFed.Entities.ShedLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CompleteShed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReptileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.HasIndex("ReptileId");

                    b.ToTable("ShedLogs");
                });

            modelBuilder.Entity("ShedAndFed.Entities.WasteLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReptileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LogId");

                    b.HasIndex("ReptileId");

                    b.ToTable("WasteLogs");
                });

            modelBuilder.Entity("ShedAndFed.Entities.FeedingLog", b =>
                {
                    b.HasOne("ShedAndFed.Entities.Reptile", "Reptile")
                        .WithMany("Feedings")
                        .HasForeignKey("ReptileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reptile");
                });

            modelBuilder.Entity("ShedAndFed.Entities.ShedLog", b =>
                {
                    b.HasOne("ShedAndFed.Entities.Reptile", "Reptile")
                        .WithMany("Sheds")
                        .HasForeignKey("ReptileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reptile");
                });

            modelBuilder.Entity("ShedAndFed.Entities.WasteLog", b =>
                {
                    b.HasOne("ShedAndFed.Entities.Reptile", "Reptile")
                        .WithMany("Wastes")
                        .HasForeignKey("ReptileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reptile");
                });

            modelBuilder.Entity("ShedAndFed.Entities.Reptile", b =>
                {
                    b.Navigation("Feedings");

                    b.Navigation("Sheds");

                    b.Navigation("Wastes");
                });
#pragma warning restore 612, 618
        }
    }
}
